import Head from 'next/head'
import styles from '../styles/Home.module.css'
// import { FaFacebook, FaLinkedin, FaGoogle, FaRegEnvelope} from "react-icons/fa";
// import { MdLockOutline } from "react-icons/md";
import Hero from '../components/Hero';
import Slider from '../components/Slider';
import ContactUs from '../components/ContactUs';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Welocme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="Headings" message="messages something to be written here about the product or complany"  ></Hero>
      <Slider/>
      <ContactUs/>
    </div>
  )
}
